version: "3.8"
services:
  app:
    container_name: cyberCine_app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - database-dev-cibercine
    networks:
      - hotel-network
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - hotel-network
  database-dev-cibercine:
    image: mysql:8.0
    container_name: database-dev
    restart: always
    volumes:
      - mysql-volume-2:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --max_allowed_packet=67108864
    environment:
      - MYSQL_DATABASE=db_hotelpe
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=America/Lima
    networks:
      - hotel-network
volumes:
  mysql-volume-2:
networks:
  hotel-network: