version: "3.8"
services:
  app:
    container_name: cyberCine_app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - cyberCine-network
networks:
  cyberCine-network: